server {
  listen 80;
  server_name _;

  location / {
    root /app/dist;
    try_files $uri $uri/ /index.html;
    index index.html index.htm;
  }

  # Cache de assets compilados (JS, CSS)
  location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
    root /app/dist;
    expires 1y;
    add_header Cache-Control "public, immutable";
  }
}
